set(CTEST_PROJECT_NAME "MPTK")
set(CTEST_NIGHTLY_START_TIME "20:00:00 CEST")

set(CTEST_DROP_METHOD "http")
set(CTEST_DROP_SITE "cdash.inria.fr")
set(CTEST_DROP_LOCATION "/CDash/submit.php?project=MPTK")
set(CTEST_DROP_SITE_CDASH TRUE)
